server:
  port: 9876

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bear?serverTimeZone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver